### ISSUE TITLE
Syntax error in `.env` file

### ISSUE THREAD

**Issue by domwhewell-sage** [GhostManager/cobalt_sync#8]
Hi I am having trouble starting the cobalt_parser container

Here are the logs:
```bash
Error: unknown command "\"monitor" for "cobalt-parser"

Did you mean this?
        monitor

Run 'cobalt-parser --help' for usage.
```

I have tried removing the `"` from that line in the `.env` file but no dice

This is my env file
```bash
GHOSTWRITER_API_KEY="asdfghjkl1234567890"
GHOSTWRITER_URL="https://ghostwriter.local"
GHOSTWRITER_OPLOG_ID="1"
COBALT_PARSER_COMMAND="monitor /logs -s http://cobalt_web:9000 --onlyHashes --reprocess"
COBALT_LOGS_PATH=/opt/cobaltstrike/logs
WEBHOOK_DEFAULT_URL=
WEBHOOK_DEFAULT_ALERT_CHANNEL=
```

**Comment by its-a-feature** [comment]
What's your Docker and docker compose versions?

**Comment by domwhewell-sage** [comment]
Hi @its-a-feature,
I'm running on ubuntu LTS
```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```
And my docker version is `Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1`
The docker-compose version is `docker-compose version 1.25.0, build unknown`

**Comment by its-a-feature** [comment]
Are you able to upgrade your docker-compose version? You need at least version 1.26

**Comment by domwhewell-sage** [comment]
Yep I should be able to upgrade the server to 22.04 which I assume will have a higher version available. Thanks will update if that fixes it 👍
